services:
  java-app:
    build: java-app
    depends_on:
      - ibm-mq
      - mongo-db
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      mode: replicated

  mongo-db:
    image: mongo:7.0.0
    ports:
      - "3128:3128"

  ibm-mq:
    image: ibmcom/mq:9
    ports:
      - "4320:4320"